#!/bin/bash
uglifyjs raphael.donutpiechart.js \
--screw-ie8 \
--output "raphael.donutpiechart.min.js" \
--compress "if_return,unused,booleans,comparisons,dead_code,sequences" \
--lint \
--mangle \
--verbose

